trigger:
  branches:
    include:
    - master
  paths:
    include:
    - prk2.py 
jobs:
- job: myjob
  timeoutInMinutes: 300

  pool:
    vmImage: 'ubuntu-22.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
  
  - script: python -m pip install --upgrade pip
    displayName: 'Install dependencies'
  
#  - script: pip install pyyaml requests  tqdm colorama six requests_toolbelt
#    displayName: 'Install requirements'
    
  - script:  python3 prk2.py
    displayName: el
